---

- name: prepare systemd unit for xenial
  template:
    src: systemd-unit.j2
    dest: /etc/systemd/system/proxysql.service
  notify:
    - reload proxysql unit
    - enable proxysql service
    - restart proxysql service
  when: ansible_distribution_release == 'xenial'

- name: create systemd override for non-xenial distros
  block:
    - name: create proxysql.service.d directory
      file:
        path: /etc/systemd/system/proxysql.service.d
        state: directory
        mode: 0755
    - name: create proxysql.service override
      template:
        src: proxysql-override.j2
        dest: /etc/systemd/system/proxysql.service.d/override.conf
      notify:
        - reload proxysql unit
        - restart proxysql service
  when: ansible_distribution_release != 'xenial'

- name: create proxysql.cnf
  template:
    src: "{{ proxysql_cnf_src|default('files/proxysql/proxysql.cnf') }}"
    dest: /etc/proxysql.cnf
    owner: root
    group: proxysql
    mode: 0640
  notify: restart proxysql service

- name: create .pxcli.cnf
  template:
    src: pxcli-cnf.j2
    dest: /root/.pxcli.cnf
    owner: root
    group: root
    mode: 0600
