---

- name: install
  include_tasks: install.yml
  when: proxysql_setup == "full" or proxysql_setup == "install"

- name: configure
  import_tasks: configure.yml
  when: proxysql_setup == "full" or proxysql_setup == "configure"
